# Generated by Django 4.0.1 on 2022-01-15 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=60, verbose_name='Denominación social/Apellidos y nombre')),
                ('n_comercial', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre comercial')),
                ('calle', models.CharField(max_length=100, verbose_name='Calle')),
                ('calle2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Calle 2')),
                ('ciudad', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ciudad')),
                ('provincia', models.CharField(blank=True, max_length=20, null=True, verbose_name='Provincia')),
                ('cp', models.CharField(blank=True, max_length=8, null=True, verbose_name='Código Postal')),
                ('pais', models.CharField(default='España', max_length=20, verbose_name='País')),
                ('nif', models.CharField(error_messages={'unique': 'Ya existe otro contacto con ese NIF'}, max_length=15, unique=True, verbose_name='NIF')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('tfno', models.CharField(blank=True, max_length=12, null=True, verbose_name='Teléfono ejemplo +34000000000')),
                ('movil', models.CharField(blank=True, max_length=12, null=True, verbose_name='Móvil ejemplo +34000000000')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de contacto')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('tfno', models.CharField(blank=True, max_length=12, null=True, verbose_name='Teléfono ejemplo +34000000000')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='contactos.empresa')),
            ],
        ),
    ]
